# Generated by Django 6.0.3 on 2026-04-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothetical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hypothetical.user'),
        ),
    ]
