# Generated by Django 6.0.3 on 2026-04-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypothetical', '0002_alter_user_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='partner',
            new_name='partner_id',
        ),
    ]
