# Generated by Django 6.0.3 on 2026-04-05 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothetical', '0003_rename_partner_user_partner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='partner_id',
            new_name='partner',
        ),
        migrations.AlterField(
            model_name='question',
            name='edittable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 5, 13, 3, 34, 899276, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
